[package]
name = "pe-split-map"
version = "0.1.0"
edition = "2024"

[dependencies]
iced-x86 = { version = "1.21.0", features = ["code_asm"] }
winapi = { version = "0.3.9", features = ["winnt"] }
rand = "0.9.2"